### ISSUE TITLE
Unexpected error when content has the same name as the sequence

### ISSUE THREAD

**Issue by adfoster-r7** [sdaubert/rasn1#12]
Hi there,

I was just looking at using RASN1 to parse some Kerberos models from the [spec](https://www.rfc-editor.org/rfc/rfc4120.html#section-5), and I just wanted to document an issue I ran into where the content had the same name as the sequence:

```asn1
    Int32           ::= INTEGER (-2147483648..2147483647)
                        -- signed values representable in 32 bits

   Checksum        ::= SEQUENCE {
           cksumtype       [0] Int32,
           checksum        [1] OCTET STRING
   }
```

Initially I implemented this as:

```ruby
require 'rasn1'
require 'openssl'

checksum_input = (
  "\x30\x19\xa0\x03\x02\x01\x07\xa1\x12\x04\x10\x9e\xf0\x84\xd6\x81" \
  "\xe5\x16\x02\x32\xb1\xc3\x4e\xad\x83\x1d\x43"
).b

class CheckSum < RASN1::Model
  sequence :checksum,
           content: [
             integer(:cksumtype, explicit: 0, constructed: true),
             octet_string(:checksum, explicit: 1, constructed: true)
           ]
end

pp RASN1.parse(checksum_input)
pp OpenSSL::ASN1.decode(checksum_input)
pp CheckSum.parse(checksum_input)
```

But it gives an unexpected runtime error:

```
/Users/user/.rvm/gems/ruby-3.0.2@foo/gems/rasn1-0.10.0/lib/rasn1/types/base.rb:473:in `raise_id_error': checksum: Expected CONTEXT CONSTRUCTED 0x1 (0xa1) but get UNIVERSAL CONSTRUCTED SEQUENCE (RASN1::ASN1Error)
        from /Users/user/.rvm/gems/ruby-3.0.2@foo/gems/rasn1-0.10.0/lib/rasn1/types/base.rb:431:in `check_id'
        from /Users/user/.rvm/gems/ruby-3.0.2@foo/gems/rasn1-0.10.0/lib/rasn1/types/base.rb:204:in `parse!'
        from /Users/user/.rvm/gems/ruby-3.0.2foo/gems/rasn1-0.10.0/lib/rasn1/model.rb:327:in `parse!'
        from /Users/user/.rvm/gems/ruby-3.0.2@foo/gems/rasn1-0.10.0/lib/rasn1/model.rb:256:in `parse'
        from foo.rb:102:in `<main>'
```

I realized I was able to get this working by renaming the `checksum` octet_string in the content:

```diff
class CheckSum < RASN1::Model
  sequence :checksum,
           content: [
             integer(:cksumtype, explicit: 0, constructed: true),
-             octet_string(:checksum, explicit: 1, constructed: true)
+             octet_string(:foo, explicit: 1, constructed: true) 
           ]
end
```

Which was then parsed as expected:

```
(CheckSum) checksum SEQUENCE:
  cksumtype CONTEXT [0] EXPLICIT INTEGER: 7
  foo CONTEXT [1] EXPLICIT OCTET STRING: "\x9E\xF0\x84\xD6\x81\xE5\x16\x022\xB1\xC3N\xAD\x83\x1DC"
```

I wasn't sure if this is user error or not, but thought it was worth sharing

**Comment by sdaubert** [comment]
@adfoster-r7 Sorry for the lmate response.

A hash is used internally to store all ASN.1 type. The keys are the field names. So, with your last definition, the first definition of `checksum` is erased by the second one. Then, the parser begins to parse from the root element (named `checksum` here) and uses the element from the hash. But this element is no more a Sequence but an OctetString.

In a Model, you must not have same name for different elements.

**Comment by adfoster-r7** [comment]
Thanks! Would it makes sense for me to send a pull request for validation for this scenario?

**Comment by sdaubert** [comment]
Yes.
